name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your default branch or any branch you want to trigger builds from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=$(pwd)/kubeconfig.yaml
          kubectl config use-context minikube  # Use the context from your kubeconfig

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f wisecow-deployment.yaml
          kubectl apply -f wisecow-service.yaml
          kubectl apply -f wisecow-ingress.yaml

      - name: Cleanup
        run: |
          rm kubeconfig.yaml  # Optional: Clean up the kubeconfig file after the deployment
