name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      run: |
        docker build -t vishnuyadav799/wisecow-app:latest .
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: |
        docker push vishnuyadav799/wisecow-app:latest

    - name: Setup SSH
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
        chmod 600 ec2_key.pem

    - name: Copy Kubernetes Manifests to EC2
      run: |
        scp -i ec2_key.pem -o StrictHostKeyChecking=no -r ./wisecow-deployment.yaml ./wisecow-service.yaml ./wisecow-ingress.yaml ubuntu@13.235.62.34:~/

    - name: SSH into EC2 and Deploy
      run: |
        ssh -i ec2_key.pem -o StrictHostKeyChecking=no ubuntu@13.235.62.34 << 'EOF'
          # Set KUBECONFIG
          export KUBECONFIG=$HOME/.kube/config

          # Verify Kubernetes context
          kubectl config current-context

          # Deploy to Kubernetes
          kubectl apply -f wisecow-deployment.yaml
          kubectl apply -f wisecow-service.yaml
          kubectl apply -f wisecow-ingress.yaml
        EOF

    - name: Cleanup SSH Key
      run: |
        rm -f ec2_key.pem
